### PR TITLE
Update CONTRIBUTOR_ROLES.md

### LINKED ISSUE #8: Community participation roles
- [x] 'Roles' & 'stepping down' should be same level
- [x] Community participant and contributor squash into one
- [x] Roles -> Levels at top community member/contributor, spotlight contributor, maintainer, owner
- [ ] Specialised roles -> Community manager (make more generic), Invited Experts,
- [ ] Move to MDN (do last after final edit)

### PR DESCRIPTION
**Pull request by dipikabh**
Fixes https://github.com/mdn/project-template/issues/8

- Added the section "Processes" and moved all nomination processes there
- Made all the role sections consistent to only have the "Requirements" and "Privileges" subsections

Questions in the "Maintainer" and related process section

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks, Dipika, taking a look 👀

**Comment by bsmth** [comment]
I hope you don't mind, I made some minor changes directly on the branch. I think we should merge and take a look at it again with a fresh perspective 👍🏻 

The content is good, I'm curious what we can put on MDN and how much of this we want repeated across repos. Especially the process section, if we change this (even a link to issue template), we'll have to update this across many repos (max 120 😢). We should avoid this and point to our process on MDN contribution docs where we only have one source of truth for it (`mdn/content`).

**Comment by dipikabh** [comment]
> The content is good, I'm curious what we can put on MDN and how much of this we want repeated across repos. 

You're right. The intention for the cleanup here is to ultimately move it to Contributor Docs, as mentioned in the [issue](https://github.com/mdn/project-template/issues/8):
"Move to MDN (do last after final edit)"

**Comment by bsmth** [comment]
> "Move to MDN (do last after final edit)"

Gotcha, thank you! 👍🏻

**Pull request merged**
